// Generated by https://quicktype.io

export interface CarouselMain {
    id:               number;
    descripcion:      string;
    nombre:           string;
    nombreTablet:     string;
    nombreMobile:     string;
    estado:           number;
    orden:            number;
    link:             string;
    fechaLanzamiento?: null | string;
    fechaVencimiento?: null | string;
    ventana:          boolean;
}
