// Generated by https://quicktype.io

export interface Characteristics {
    id_producto:                         number;
    modelo?:                             null | string;
    cpus?:                               string;
    SATA?:                               number;
    marca?:                              Marca | null;
    _4pines?:                            number;
    _4plus?:                             number;
    wmax?:                               number;
    _24pines?:                           number;
    PCI?:                                number;
    nro_pcie?:                           number;
    PCIE1X?:                             number;
    nro_agp?:                            number;
    IDE?:                                number;
    tipo_multiplaca?:                    string;
    DDR?:                                number;
    DDR2?:                               number;
    DDR3?:                               number;
    DDR4?:                               number;
    DDR5?:                               number;
    Chipsets?:                           string;
    disponible?:                         number | null;
    vga?:                                number;
    HDMI?:                               number;
    dvi?:                                string;
    DP?:                                 number;
    w?:                                  number | null;
    Floppy?:                             number;
    USB?:                                number;
    Factor?:                             Factor;
    sodimm?:                             number;
    m2?:                                 number;
    con_micro?:                          number;
    id_sub_cate?:                        number;
    tipo?:                               string;
    activo?:                             number;
    wifi_integrada?:                     number;
    sistema_rgb?:                        SistemaRGB | null;
    usb20_trasero?:                      number;
    usb30_trasero?:                      number;
    usb31_trasero?:                      number;
    ps2?:                                number;
    lan?:                                LAN;
    placa_audio?:                        string;
    anclaje?:                            string;
    bios_flashback?:                     number;
    usb_32_trasero?:                     number;
    usb_type_c?:                         number;
    pci_e_x4?:                           number;
    m2_sata?:                            number;
    m2_nvme?:                            number;
    tipo_memoria?:                       Tipo;
    slot_memoria?:                       number;
    cores?:                              number;
    clock?:                              number;
    cooler?:                             number;
    familia?:                            string;
    l1?:                                 null | string;
    l2?:                                 null | string;
    l3?:                                 null | string;
    tecnologia?:                         null | string;
    cate_cpu?:                           number;
    chipset_gpu?:                        string;
    nivel_cpu_deprecado?:                null;
    nivel_gpu?:                          number | null;
    hilos?:                              number;
    turbo?:                              number | null;
    sockets?:                            string;
    altura?:                             number;
    tipo_gab?:                           Factor;
    espacios_120mm?:                     string;
    espacios_140mm?:                     number;
    altura_real?:                        string;
    nro_coolers?:                        number;
    cooler_base?:                        number;
    tipo_disipacion?:                    TipoDisipacion | null;
    color_iluminacion?:                  null | string;
    ruido?:                              null;
    ruido_max?:                          null | string;
    TDP?:                                null | string;
    tam_cooler?:                         null | string;
    capacidad?:                          number;
    disipador?:                          number;
    velocidad?:                          string;
    slot?:                               number;
    latencia_cl?:                        number;
    voltaje?:                            number;
    disipacion_alta?:                    number;
    chipset?:                            string;
    vel_core?:                           number | null;
    vel_mem?:                            number | null;
    tipo_mem?:                           TipoMem;
    puente_id?:                          number | null;
    doble_puente?:                       number;
    _6pines?:                            number;
    _2plus?:                             number;
    hdmi?:                               number;
    DVI?:                                number | null;
    w_total?:                            number;
    dvi_analogico?:                      number;
    rca?:                                number;
    svideo?:                             number | null;
    usbtypec?:                           number | null;
    video_in?:                           number;
    mem_bits?:                           number;
    ancho?:                              number | null | string;
    largo?:                              number | null;
    espesor?:                            number | null;
    backplate?:                          number;
    block_vga_water?:                    number;
    vel_cor_turbo?:                      number | null;
    cant_cooler?:                        number | null;
    tipo_procesos?:                      TipoProcesos;
    cant_procesos?:                      number | null;
    tasa_transf?:                        number;
    cache?:                              number;
    rpm?:                                number;
    dimension?:                          Dimension;
    tipo_almacenamiento?:                TipoAlmacenamiento;
    formato_notebook?:                   number;
    velocidad_lectura_secuencial?:       number | null;
    velocidad_escritura_secuencial?:     number | null;
    velocidad_lectura_random?:           number | null;
    velocidad_escritura_random?:         number | null;
    vida_util?:                          number | null;
    tbw?:                                number | null;
    categoria_tamaño?:                   CategoriaTamaño;
    prod_hdcol?:                         null;
    interfaz?:                           Interfaz;
    kit?:                                number;
    kit_detalle?:                        null | string;
    tipo_fuente?:                        TipoFuente;
    id_fuente?:                          number;
    posicion_fuente_superior?:           number;
    tipo_mother?:                        TipoMother;
    altura_cpu?:                         number;
    unidades_opticas?:                   number;
    cf_80mm?:                            number;
    cf_120mm?:                           number;
    cf_140mm?:                           number;
    cf_200mm?:                           number;
    cf_80mm_incluidos?:                  number;
    cf_120mm_incluidos?:                 number;
    cf_140mm_incluidos?:                 number;
    cf_200mm_incluidos?:                 number;
    cf_2x120mm_continuos?:               number;
    cf_2x140mm_continuos?:               number;
    cf_3x120mm_continuos?:               number;
    cf_3x140mm_continuos?:               number;
    cf_continuos_con_espacio_disipador?: number;
    slots?:                              number;
    ancho_maximo_vga?:                   number;
    unidades_2_5?:                       number;
    unidades_3_5?:                       number;
    unidades_3_25?:                      number;
    alto?:                               number | null | string;
    profundidad?:                        number | null | string;
    largo_maximo_vga?:                   number;
    usb30_frontal?:                      number;
    usb20_frontal?:                      number;
    usb31_frontal?:                      number;
    conector_usb30_interno?:             number;
    conector_usb20_interno?:             number;
    conector_usb31_interno?:             number;
    audio_ac97_frontal?:                 number;
    audio_hd_frontal?:                   number;
    lector_tarjetas_frontal?:            number;
    ventana?:                            number;
    tipo_de_ventana?:                    TipoDeVentana | null;
    iluminacion?:                        null | string;
    color?:                              string;
    Soporte_GPU_Vertical?:               number;
    riser?:                              number;
    controlador_de_fans?:                ControladorDeFans | null;
    Controlador_RGB?:                    number;
    Cover_fuente?:                       number;
    altura_ccpu?:                        number;
    tipo_ponderado?:                     null;
    factor?:                             Factor;
    w_real?:                             number;
    w_nominal?:                          number;
    pines_pcie?:                         number;
    pines_pcieplus?:                     number;
    incluye_cable?:                      number;
    compatible_abajo?:                   number;
    certi80plus?:                        TresD | null;
    ModoHibrido?:                        number;
    tipocableado?:                       Tipocableado;
    amper12v?:                           number | null;
    sata?:                               number;
    molex?:                              number | string;
    floppy?:                             null;
    digital?:                            number;
    pulgadas?:                           number;
    pulgadas_visibles?:                  number;
    resolucion?:                         string;
    max_frecuenta?:                      number;
    radio_constraste_estativo?:          number | null;
    radio_constraste_dynamico?:          number | null;
    tipo_de_ilumunacion?:                null;
    brillo?:                             number | null;
    colores?:                            number | null | string;
    tiempo_respuesta?:                   number;
    angulo_vision_horizontal?:           number;
    angulo_vision_vertical?:             number;
    vida_backlight?:                     number | null;
    tipo_de_panel?:                      string;
    entra_3_5mm?:                        number;
    salida_3_5mm?:                       number;
    VGA?:                                number;
    cant_parlantes?:                     number;
    potencia_x_parlante?:                number | null;
    ConsumoMax?:                         number | null;
    VESA?:                               VESA;
    peso?:                               number | null | string;
    sintonizador_analogico?:             number;
    sintonizador_tda?:                   number;
    USB20?:                              number;
    USB30?:                              number;
    USB31?:                              number;
    smart?:                              number;
    control_remoto?:                     number;
    android_tv?:                         number;
    pie_desmontable?:                    number;
    cables?:                             null | string;
    nvidia_g_sync?:                      number;
    amd_freesync?:                       number;
    curvo?:                              number;
    curvatura?:                          number;
    tres_d?:                             TresD;
    tactil?:                             number;
    mini_dp?:                            number;
    display_wifi?:                       number;
    entrada_3_5_mic?:                    number;
    mini_plug_audio?:                    null | string;
    mini_plug_combinado?:                null | string;
    impedancia?:                         null | string;
    usb?:                                string;
    wifi_por_receptor?:                  string;
    wifi_por_bt?:                        string;
    tamano_parlante?:                    string;
    resp_hz_min?:                        string;
    resp_hz_max?:                        string;
    sensibilidad?:                       null | string;
    mini_plug_mic?:                      null | string;
    usb_power?:                          string;
    disp_compatible?:                    string;
    largo_cable?:                        null | string;
    base?:                               string;
    mic_resp_hz_min?:                    null | string;
    mic_resp_hz_max?:                    null | string;
    mic_sensibilidad?:                   null;
    mic_tipo?:                           ControlLED | null;
    mic_cancelacion?:                    string;
    mic_tipo_captacion?:                 MicTipoCaptacion | null;
    surround?:                           string;
    wireless?:                           Wireless;
    con_mic?:                            string;
    virtual_real?:                       VirtualReal;
    formato?:                            Formato;
    dimensiones?:                        number;
    cantidad?:                           number;
    max_speed?:                          number | null;
    regular_speed?:                      number;
    LED?:                                number;
    ColorLED?:                           string;
    Pines?:                              number;
    max_ruido?:                          number | null;
    flujo_maximo?:                       null;
    hue_compatible?:                     number;
    presion_estatica?:                   number | null;
    incluye_controladora_rgb?:           number;
    cantidad_de_botones?:                number;
    dpi_ajustable?:                      string;
    dpi_minimo?:                         null | string;
    dpi_maximo?:                         number;
    frecuencia_de_respuesta?:            null | string;
    sistema_de_pesas?:                   string;
    peso_de_las_pesas?:                  null | string;
    cantidad_de_pesas?:                  null | string;
    tipo_switch?:                        TipoSwitch | null;
    tipo_sensor?:                        TipoSensor | null;
    sensor?:                             null | string;
    tecnologias_compatibles?:            TecnologiasCompatibles | null;
    bateria_interna?:                    string;
    pilas?:                              null | string;
    inalambrico?:                        number;
    tipo_cable?:                         TipoCable | null;
    cable_largo?:                        null | string;
    cable_desmontable?:                  string;
    teconologiawifi?:                    null | string;
    usb_requeridos?:                     null | string;
    incluye_receptor?:                   string;
    orientacion?:                        Orientacion | null;
    ps2_requerido?:                      string;
    sistema_recargable?:                 string;
    velocidad_maxima?:                   number | null;
    aceleracion_maxima?:                 number | null;
    funda?:                              number | string;
    consolas_compatibles?:               null;
    base_de_carga?:                      string;
    iluminancion_colores?:               IluminancionColores | null;
    procesador?:                         Procesador | null;
    tipo_de_agarre?:                     null | string;
    agarre_palm_grip?:                   number;
    agarre_claw_grip?:                   number;
    agarre_finger_grip?:                 number | null;
    agarre_ergonomico?:                  number | null;
    en_combo_con_pad?:                   number | null;
    grosor?:                             number;
    tipo_superficie?:                    TipoSuperficie;
    categoria?:                          string;
    cargas_wifi?:                        string;
    hub_usb?:                            string;
    req_usb?:                            string;
    control_Led?:                        ControlLED | null;
    swich_type?:                         null | string;
    switch_spe?:                         null | string;
    tipo_teclado?:                       TipoTeclado;
    con_pad_numerico?:                   string;
    puertos_usb_hb?:                     null | string;
    cable_extraible?:                    string;
    antisalpicadura?:                    string;
    idioma?:                             Idioma | null;
    distribucion?:                       Distribucion | null;
    antighosting?:                       string;
    reposamunecas?:                      string;
    reposamunecas_extraible?:            string;
    cantidad_macros_cargar?:             null | string;
    cantidad_teclas_en_simultaneo?:      null | string;
    conexion?:                           string;
    puertos_ps2?:                        number;
    bluetooth?:                          number;
    receptor_bluetooth?:                 number;
    wifi?:                               string;
    bateria?:                            Bateria | null;
    tipo_mecanicos?:                     TipoMecanicos;
    NKey_Rollover?:                      string;
    audio_hub?:                          string;
    material?:                           Material;
    polling_rate?:                       null | string;
    tiempo_de_respuesta?:                null | string;
    memoria?:                            null | string;
    largo_del_cable?:                    null | string;
    touchpad?:                           string;
    alcance_wifi?:                       null;
    pilas_incluida?:                     null | string;
    ancho_sin_pad?:                      null;
    nivel_cpu?:                          number;
    cantidad_ram_integrada?:             number | null;
    slot1_disponible?:                   number;
    slot2_disponible?:                   number;
    slot_integrado_disponible?:          null;
    pulgadas_display?:                   number;
    optico?:                             Optico;
    slot_m2?:                            number;
    capacidad_hd?:                       number;
    tipo_m2?:                            TipoM2 | null;
    sistema_operativo?:                  SistemaOperativo;
    idioma_teclado?:                     IdiomaTeclado;
    puertos_hdmi?:                       number;
    puertos_mini_hdmi?:                  number;
    puertos_vga?:                        number;
    puertos_dp?:                         number;
    puertos_usb_2_0?:                    number;
    puertos_usb_3_0?:                    number;
    puertos_usb_3_1_a?:                  number;
    puertos_usb_3_1_c?:                  number;
    con_bluethooth?:                     number;
    tipo_wifi?:                          TipoWifi;
    puertos_lan?:                        PuertosLAN;
    tipo_display?:                       TipoDisplay | null;
    tipo_cpu?:                           TipoCPU;
    tipo_gpu?:                           TipoGPU;
    resolucion_display?:                 ResolucionDisplay;
    iluminacion_teclado?:                number;
    bateria_extraible?:                  number;
    peso_sin_bateria?:                   null;
    cantidad_ram_slot1?:                 number | null;
    cantidad_ram_slot2?:                 number | null;
    tipo_ram?:                           Tipo;
    modelo_gpu?:                         string;
    gpu_dedicado?:                       number;
    modelo_cpu?:                         string;
    familia_cpu?:                        string;
    capacidad_ssd?:                      number | null;
    idioma_sistema_operativo?:           null | string;
    touch?:                              string;
    padnum?:                             string;
    webcam?:                             number;
    color_luz_teclado?:                  null | string;
    lector_de_memorias?:                 number;
    mem_gpu?:                            number | null;
    lector_de_huella?:                   number;
    tasa_refesco?:                       number | null;
    formato_ram?:                        FormatoRAM;
}

export enum Factor {
    Atx = "ATX",
    EAtx = "E-ATX",
    Itx = "ITX",
    MAtx = "M-ATX",
}

export enum VESA {
    Empty = "-",
    NoIncluye = "No incluye",
    The100X100 = "100x100",
    The200X200 = "200x200",
    The400X300 = "400x300",
    The400X400 = "400x400",
    The75X75 = "75x75",
}

export enum Bateria {
    BateríaInterna = "Batería interna",
    Empty = "",
    The2PilasAAA = "2 pilas AAA",
}

export enum CategoriaTamaño {
    Empty = "",
    The120GB = "120GB",
    The240GB250GB256GB = "240GB 250GB 256GB",
    The480GB500GB512GB = "480GB 500GB 512GB",
    The960GB1000GB1024GB1TB = "960GB 1000GB 1024GB 1TB",
}

export enum TresD {
    No = "No",
    The80PLUSBronze = "80 PLUS Bronze",
    The80PLUSGold = "80 PLUS Gold",
    The80PLUSPlatinum = "80 PLUS Platinum",
    The80Plus = "80 PLUS",
}

export enum ControlLED {
    Desmontable = "Desmontable",
    Integrado = "Integrado",
    Retráctil = "Retráctil",
}

export enum ControladorDeFans {
    Empty = "-",
    Externo = "externo",
    Interno = "interno",
}

export enum Dimension {
    M2 = "M2",
    The25 = "2.5",
    The35 = "3.5",
}

export enum Distribucion {
    España = "España",
    EstadosUnidos = "Estados Unidos",
    Latinoamerica = "Latinoamerica",
}

export enum Formato {
    Headset = "Headset",
}

export enum FormatoRAM {
    Sodimm = "SODIMM",
}

export enum Idioma {
    Español = "Español",
    Inglés = "Inglés",
}

export enum IdiomaTeclado {
    Empty = "",
    Español = "Español",
    Ingles = "Ingles",
}

export enum IluminancionColores {
    Azul = "Azul",
    RGB = "RGB",
    Rainbow = "Rainbow",
    SinIluminación = "Sin Iluminación",
}

export enum Interfaz {
    NVMe = "NVMe",
    SATA = "SATA",
}

export enum LAN {
    GigabitLAN101001000MBS = "Gigabit LAN 10/100/1000 Mb/s",
    The10GBS = "10 Gb/s",
    The1GBS = "1 Gb/s",
    The25GBS = "2.5 Gb/s",
    The25GigabitLAN1010010002500 = "2.5 Gigabit LAN 10/100/1000/2500",
}

export enum Marca {
    Asus = "Asus",
    Empty = "",
    Seagate = "Seagate",
    WBCaviarBlue = "WB Caviar Blue",
    Xfx = "XFX",
}

export enum Material {
    Aluminio = "Aluminio",
    AluminioPlástico = "Aluminio,Plástico",
    MetalPlástico = "Metal,Plástico",
    Plástico = "Plástico",
    PlásticoAluminio = "Plástico,Aluminio",
    PlásticoMetal = "Plástico,Metal",
}

export enum MicTipoCaptacion {
    NoEspecificado = "No especificado",
    Omnidireccional = "Omnidireccional",
    Unidireccional = "Unidireccional",
}

export enum Optico {
    SinOptico = "Sin optico",
}

export enum Orientacion {
    ParaAmbidiestros = "Para ambidiestros",
    ParaDiestros = "Para diestros",
}

export enum Procesador {
    ARMCortex32Bits = "ARM Cortex 32 bits",
    The32BitsARM = "32 bits ARM",
}

export enum PuertosLAN {
    Gigabit101001000 = "Gigabit 10/100/1000",
    No = "No",
    Si = "Si",
}

export enum ResolucionDisplay {
    The1366X768 = "1366x768",
    The1920X1080 = "1920x1080",
    The2560X1440 = "2560x1440",
}

export enum SistemaOperativo {
    Empty = "",
    FreeDOS = "FreeDOS",
    Windows10Home64Bits = "Windows 10 Home 64bits",
    Windows11Home = "Windows 11 Home",
    Windows11Pro = "Windows 11 Pro",
}

export enum SistemaRGB {
    ARGBHeader = "ARGB Header",
    ARGBHeaderRGBHeader = "ARGB Header,RGB Header",
    Empty = "",
    NoIncluye = "No Incluye",
    PropioDelGabinete = "Propio del gabinete",
    RGBHeader = "RGB Header",
    RGBHeaderARGBHeader = "RGB Header,ARGB Header",
    SistemaRGBNoIncluye = "No incluye",
}

export enum TecnologiasCompatibles {
    LogitechGHUB = "Logitech G HUB",
    Powerplay = "POWERPLAY",
    SoftwarePropio = "Software propio",
}

export enum TipoAlmacenamiento {
    Mecánico = "Mecánico",
    Sólido = "Sólido",
}

export enum TipoCable {
    AscendedCordUltraFlexible = "Ascended Cord (ultra-flexible)",
    MalladoDeTela = "Mallado de tela",
    ParacordUltraLiviano = "Paracord Ultra Liviano",
    Plástico = "Plástico",
    TelaMallada = "Tela mallada",
}

export enum TipoCPU {
    AMD = "AMD",
    Intel = "Intel",
}

export enum TipoDeVentana {
    Acrílico = "Acrílico",
    MetalMesh = "Metal Mesh",
    MetalMeshTG = "Metal Mesh / TG",
    SinVentana = "Sin ventana",
    VidrioTemplado = "Vidrio templado",
}

export enum TipoDisipacion {
    Aire = "Aire",
    Watercooling = "Watercooling",
}

export enum TipoDisplay {
    IPS = "IPS",
    OLED = "OLED",
    Tn = "TN",
}

export enum TipoFuente {
    Atx = "ATX",
    Externa = "externa",
    Interna = "interna",
    Sfx = "SFX",
}

export enum TipoGPU {
    AMDIntegratedGraphics = "AMD Integrated Graphics",
    IntelHDGraphic = "Intel HD Graphic",
    IntelIntegratedGraphics = "Intel Integrated Graphics",
    NVidiaGeForce = "nVidia GeForce",
    NvidiaGeForce = "Nvidia GeForce",
}

export enum TipoM2 {
    Nvme = "NVME",
}

export enum TipoMecanicos {
    Mecánico = "Mecánico",
    Membrana = "Membrana",
    OptoMecanico = "Opto-Mecanico",
}

export enum TipoMem {
    Gddr5 = "GDDR5",
    Gddr6 = "GDDR6",
    Gddr6X = "GDDR6X",
}

export enum Tipo {
    Ddr4 = "DDR4",
    Ddr5 = "DDR5",
}

export enum TipoMother {
    AtxItxMAtx = "ATX,ITX,M-ATX",
    AtxMAtxItx = "ATX,M-ATX,ITX",
    Itx = "ITX",
    ItxAtxEAtxMAtx = "ITX,ATX,E-ATX,M-ATX",
    ItxAtxMAtx = "ITX,ATX,M-ATX",
    ItxMAtx = "ITX,M-ATX",
    ItxMAtxAtx = "ITX,M-ATX,ATX",
    ItxMAtxAtxEAtx = "ITX,M-ATX,ATX,E-ATX",
    ItxMAtxAtxEAtxLxAtx = "ITX,M-ATX,ATX,E-ATX,LX-ATX",
}

export enum TipoProcesos {
    Cuda = "CUDA",
    Empty = "",
    Stream = "Stream",
}

export enum TipoSensor {
    Óptico = "Óptico",
}

export enum TipoSuperficie {
    CueroSintético = "Cuero sintético",
    Rígido = "Rígido",
    Tela = "Tela",
}

export enum TipoSwitch {
    Omron = "Omron",
}

export enum TipoTeclado {
    Compacto60 = "Compacto 60%",
    Compacto70 = "Compacto 70%",
    CompactoTKL = "Compacto TKL",
    Completo = "Completo",
}

export enum TipoWifi {
    NormaAC = "Norma AC",
    NormaAX = "Norma AX",
}

export enum Tipocableado {
    CablesFijos = "Cables fijos",
    FullModular = "Full Modular",
    SemiModular = "Semi Modular",
}

export enum VirtualReal {
    Real = "Real",
    Virtual = "Virtual",
}

export enum Wireless {
    Cableado = "Cableado",
    Inalámbrico = "Inalámbrico",
}
