// Generated by https://quicktype.io

export interface Marca {
    id:                         number;
    nombre:                     string;
    marca_nombre_alias?:         string;
    marca_nombre_no_ponderado?:  string;
    garantia_oficial:           number;
    garantia_meses_por_defecto: number;
    garantia_meses_propia:      number;
    garantia_datos?:             null | string;
}
