import { Navbar } from '@/components/navbar';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { TanStackProvider } from '../plugins/TanstackProviders';
import "tw-elements/dist/css/tw-elements.min.css";


import { Montserrat, Open_Sans } from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-opensans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
  return (
    <html lang="en" className={`${montserrat.variable} ${openSans.variable} font-montserrat`}>
      <body className='h-screen bg-gray-100'>
      <Navbar />
        {/* <TanStackProvider > */}
          {children}
        {/* </TanStackProvider> */}
     
      </body>
    </html>
  )
}
