import { Navbar } from '@/components/navbar';
import './globals.css'
import type { Metadata } from 'next'
// import { TanStackProvider } from '../plugins/TanstackProviders';
import "tw-elements/dist/css/tw-elements.min.css";


import { Montserrat, Open_Sans } from 'next/font/google'
import { Slider } from '@/components/slider';
import { MainHeader } from '@/components/mainheader';
import { CarouselMarcas } from '@/components/carouselMarcas';
import { Footer } from '@/components/footer';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
})
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-opensans',
})

export const metadata: Metadata = {
  title: 'COMPRA GAMER | Compra Gamer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en" className={`${montserrat.variable} ${openSans.variable} font-montserrat`}>
      <head>
        <link rel="icon" href="/icono.ico" sizes='any' />
      </head>
      <body className='h-screen bg-gray-100'>
        <header>
          <Slider />
          <MainHeader />
          <Navbar />
        </header>
        {/* <TanStackProvider > */}
        <main>
          {children}
        </main>
        {/* </TanStackProvider> */}

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
