// Generated by https://quicktype.io

export interface BuildPC {
    mothers?:     Mother[];
    cpu?:         CPU[];
    coolercpu?:   Coolercpu[];
    mem?:         Mem[];
    video?:       Video[];
    hd?:          HD[];
    gab?:         Gab[];
    fuente?:      Fuente[];
    monitores?:   Monitore[];
    auriculares?: Auriculare[];
    card_reader?: any[];
    coolerfan?:   Coolerfan[];
    mouse?:       Mouse[];
    mousepad?:    Mousepad[];
    opticos?:     any[];
    os?:          any[];
    soportes?:    any[];
    teclados?:    Teclado[];
    extras?:      any[];
    notebooks?:   Notebook[];
}

export interface Auriculare {
    id_producto:         number;
    disponible:          number;
    mini_plug_audio:     null | string;
    mini_plug_combinado: null | string;
    impedancia:          null | string;
    usb:                 string;
    wifi_por_receptor:   string;
    wifi_por_bt:         string;
    tamano_parlante:     string;
    tipo:                string;
    resp_hz_min:         string;
    resp_hz_max:         string;
    sensibilidad:        null | string;
    colores:             Colores;
    mini_plug_mic:       null | string;
    usb_power:           string;
    disp_compatible:     string;
    largo_cable:         null | string;
    iluminacion:         ColorLuzTecladoEnum | null;
    base:                string;
    mic_resp_hz_min:     null | string;
    mic_resp_hz_max:     null | string;
    mic_sensibilidad:    null;
    mic_tipo:            MicTipo | null;
    mic_cancelacion:     string;
    mic_tipo_captacion:  MicTipoCaptacion | null;
    surround:            string;
    wireless:            Wireless;
    con_mic:             string;
    virtual_real:        VirtualReal;
    formato:             Formato;
}

export enum Colores {
    Blanco = "Blanco",
    Negro = "Negro",
    NegroAmarillo = "Negro,Amarillo",
    NegroRojo = "Negro,Rojo",
    Rosa = "Rosa",
}

export enum Formato {
    Headset = "Headset",
}

export enum ColorLuzTecladoEnum {
    RGB = "RGB",
    Rojo = "Rojo",
    SinIluminación = "Sin Iluminación",
}

export enum MicTipo {
    Desmontable = "Desmontable",
    Integrado = "Integrado",
    Retráctil = "Retráctil",
}

export enum MicTipoCaptacion {
    NoEspecificado = "No especificado",
    Omnidireccional = "Omnidireccional",
    Unidireccional = "Unidireccional",
}

export enum VirtualReal {
    Real = "Real",
    Virtual = "Virtual",
}

export enum Wireless {
    Cableado = "Cableado",
    Inalámbrico = "Inalámbrico",
}

export interface Coolercpu {
    id_producto:       number;
    sockets:           string;
    disponible:        number | null;
    altura:            number;
    tipo_gab:          TipoGab;
    espacios_120mm:    string;
    espacios_140mm:    number;
    altura_real:       string;
    nro_coolers:       number;
    w:                 number;
    cooler_base:       number;
    tipo_disipacion:   TipoDisipacion | null;
    color_iluminacion: null | string;
    ruido:             null;
    ruido_max:         null | string;
    sistema_rgb:       CoolercpuSistemaRGB | null;
    TDP:               null | string;
    tam_cooler:        null | string;
}

export enum CoolercpuSistemaRGB {
    ARGBHeader = "ARGB Header",
    Empty = "",
    NoIncluye = "No incluye",
    PropioDelGabinete = "Propio del gabinete",
    RGBHeader = "RGB Header",
}

export enum TipoDisipacion {
    Aire = "Aire",
    Watercooling = "Watercooling",
}

export enum TipoGab {
    Atx = "ATX",
    EAtx = "E-ATX",
    Itx = "ITX",
    MAtx = "M-ATX",
}

export interface Coolerfan {
    id_producto:              number;
    disponible:               number;
    dimensiones:              number;
    cantidad:                 number;
    max_speed:                number | null;
    regular_speed:            number;
    LED:                      number;
    ColorLED:                 string;
    molex:                    number;
    Pines:                    number;
    max_ruido:                number | null;
    flujo_maximo:             null;
    espesor:                  number;
    hue_compatible:           number;
    w:                        number;
    presion_estatica:         number | null;
    sistema_rgb:              CoolercpuSistemaRGB | null;
    incluye_controladora_rgb: number;
}

export interface CPU {
    id_producto:         number;
    modelo:              string;
    cores:               number;
    disponible:          number;
    w:                   number;
    clock:               number;
    tipo:                string;
    cooler:              number;
    familia:             string;
    l1:                  null | string;
    l2:                  null | string;
    l3:                  null | string;
    tecnologia:          string;
    cate_cpu:            number;
    chipset_gpu:         string;
    nivel_cpu_deprecado: null;
    nivel_gpu:           number;
    hilos:               number;
    turbo:               number | null;
}

export interface Fuente {
    id_producto:      number;
    disponible:       number;
    w_real:           number;
    w_nominal:        number;
    tipo:             TipoFuenteEnum;
    marca:            null;
    _24pines:         number;
    _4pines:          number;
    _4plus:           number;
    pines_pcie:       number;
    pines_pcieplus:   number;
    incluye_cable:    number;
    kit:              number;
    compatible_abajo: number;
    certi80plus:      TresD | null;
    ModoHibrido:      number;
    tipocableado:     Tipocableado;
    amper12v:         number | null;
    sata:             number;
    molex:            string;
    floppy:           null;
    digital:          number;
    color:            Color;
    iluminacion:      ColorLuzTecladoEnum | null;
}

export enum TresD {
    No = "No",
    The80PLUSBronze = "80 PLUS Bronze",
    The80PLUSGold = "80 PLUS Gold",
    The80PLUSPlatinum = "80 PLUS Platinum",
    The80Plus = "80 PLUS",
}

export enum Color {
    Blanco = "Blanco",
    BlancoGrisNegro = "Blanco,Gris,Negro",
    BlancoNegro = "Blanco,Negro",
    GalaxySilver = "Galaxy Silver",
    Gris = "Gris",
    Negro = "Negro",
    NegroBlanco = "Negro,Blanco",
    NegroGris = "Negro,Gris",
    NegroRojo = "Negro,Rojo",
}

export enum TipoFuenteEnum {
    Atx = "ATX",
    Sfx = "SFX",
}

export enum Tipocableado {
    CablesFijos = "Cables fijos",
    FullModular = "Full Modular",
    SemiModular = "Semi Modular",
}

export interface Gab {
    id_producto:                        number;
    kit:                                number;
    kit_detalle:                        null | string;
    disponible:                         number;
    w:                                  number;
    tipo_fuente:                        TipoFuenteEnum;
    id_fuente:                          number;
    posicion_fuente_superior:           number;
    tipo_mother:                        TipoMother;
    altura_cpu:                         number;
    unidades_opticas:                   number;
    cf_80mm:                            number;
    cf_120mm:                           number;
    cf_140mm:                           number;
    cf_200mm:                           number;
    cf_80mm_incluidos:                  number;
    cf_120mm_incluidos:                 number;
    cf_140mm_incluidos:                 number;
    cf_200mm_incluidos:                 number;
    cf_2x120mm_continuos:               number;
    cf_2x140mm_continuos:               number;
    cf_3x120mm_continuos:               number;
    cf_3x140mm_continuos:               number;
    cf_continuos_con_espacio_disipador: number;
    slots:                              number;
    ancho_maximo_vga:                   number;
    unidades_2_5:                       number;
    unidades_3_5:                       number;
    unidades_3_25:                      number;
    ancho:                              number | null;
    alto:                               number | null;
    profundidad:                        number | null;
    largo_maximo_vga:                   number;
    usb30_frontal:                      number;
    usb20_frontal:                      number;
    usb31_frontal:                      number;
    conector_usb30_interno:             number;
    conector_usb20_interno:             number;
    conector_usb31_interno:             number;
    audio_ac97_frontal:                 number;
    audio_hd_frontal:                   number;
    lector_tarjetas_frontal:            number;
    ventana:                            number;
    tipo_de_ventana:                    TipoDeVentana | null;
    iluminacion:                        GabIluminacion | null;
    color:                              Color;
    Soporte_GPU_Vertical:               number;
    riser:                              number;
    controlador_de_fans:                ControladorDeFans | null;
    Controlador_RGB:                    number;
    Cover_fuente:                       number;
    altura_ccpu:                        number;
    sistema_rgb:                        CoolercpuSistemaRGB | null;
    tipo_ponderado:                     null;
    factor:                             TipoGab;
}

export enum ControladorDeFans {
    Empty = "-",
    Externo = "externo",
    Interno = "interno",
}

export enum GabIluminacion {
    Argb = "ARGB",
    Empty = "",
    Frgb = "FRGB",
    RGB = "RGB",
}

export enum TipoDeVentana {
    Acrílico = "Acrílico",
    MetalMesh = "Metal Mesh",
    MetalMeshTG = "Metal Mesh / TG",
    SinVentana = "Sin ventana",
    VidrioTemplado = "Vidrio templado",
}

export enum TipoMother {
    AtxItxMAtx = "ATX,ITX,M-ATX",
    AtxMAtxItx = "ATX,M-ATX,ITX",
    Itx = "ITX",
    ItxAtxEAtxMAtx = "ITX,ATX,E-ATX,M-ATX",
    ItxAtxMAtx = "ITX,ATX,M-ATX",
    ItxMAtx = "ITX,M-ATX",
    ItxMAtxAtx = "ITX,M-ATX,ATX",
    ItxMAtxAtxEAtx = "ITX,M-ATX,ATX,E-ATX",
    ItxMAtxAtxEAtxLxAtx = "ITX,M-ATX,ATX,E-ATX,LX-ATX",
}

export interface HD {
    id_producto:                    number;
    marca:                          null | string;
    capacidad:                      number;
    tasa_transf:                    number;
    disponible:                     number;
    cache:                          number;
    rpm:                            number;
    tipo:                           HDTipo;
    w:                              number;
    dimension:                      Dimension;
    tipo_almacenamiento:            TipoAlmacenamiento;
    formato_notebook:               number;
    velocidad_lectura_secuencial:   number | null;
    velocidad_escritura_secuencial: number | null;
    velocidad_lectura_random:       number | null;
    velocidad_escritura_random:     number | null;
    vida_util:                      number | null;
    tbw:                            number | null;
    categoria_tamaño:               CategoriaTamaño;
    prod_hdcol:                     null;
    interfaz:                       Interfaz;
}

export enum CategoriaTamaño {
    Empty = "",
    The240GB250GB256GB = "240GB 250GB 256GB",
    The480GB500GB512GB = "480GB 500GB 512GB",
    The960GB1000GB1024GB1TB = "960GB 1000GB 1024GB 1TB",
}

export enum Dimension {
    M2 = "M2",
    The25 = "2.5",
    The35 = "3.5",
}

export enum Interfaz {
    NVMe = "NVMe",
    SATA = "SATA",
}

export enum HDTipo {
    M2 = "M2",
    SATA = "SATA",
}

export enum TipoAlmacenamiento {
    Mecánico = "Mecánico",
    Sólido = "Sólido",
}

export interface Mem {
    id_producto:     number;
    capacidad:       number;
    disponible:      number;
    disipador:       number;
    velocidad:       string;
    tipo:            PurpleTipo;
    w:               number;
    slot:            number;
    sodimm:          number;
    activo:          number;
    latencia_cl:     number;
    voltaje:         number;
    marca:           string;
    disipacion_alta: number;
}

export enum PurpleTipo {
    Ddr4 = "DDR4",
    Ddr5 = "DDR5",
}

export interface Monitore {
    id_producto:               number;
    disponible:                number;
    pulgadas:                  number;
    pulgadas_visibles:         number;
    resolucion:                Resolucion;
    max_frecuenta:             number;
    radio_constraste_estativo: number | null;
    radio_constraste_dynamico: number | null;
    tipo_de_ilumunacion:       null;
    brillo:                    number | null;
    colores:                   number | null;
    tiempo_respuesta:          number;
    angulo_vision_horizontal:  number;
    angulo_vision_vertical:    number;
    vida_backlight:            number | null;
    tipo_de_panel:             string;
    entra_3_5mm:               number;
    salida_3_5mm:              number;
    HDMI:                      number;
    DVI:                       null;
    VGA:                       number;
    DP:                        number;
    cant_parlantes:            number;
    potencia_x_parlante:       number | null;
    ConsumoMax:                number | null;
    VESA:                      VESA;
    peso:                      number;
    ancho:                     number;
    alto:                      number;
    espesor:                   number;
    sintonizador_analogico:    number;
    sintonizador_tda:          number;
    USB20:                     number;
    USB30:                     number;
    USB31:                     number;
    smart:                     number;
    control_remoto:            number;
    android_tv:                number;
    pie_desmontable:           number;
    cables:                    null | string;
    tipo_fuente:               TipoFuente;
    nvidia_g_sync:             number;
    amd_freesync:              number;
    curvo:                     number;
    curvatura:                 number;
    tres_d:                    TresD;
    tactil:                    number;
    mini_dp:                   number;
    display_wifi:              number;
    entrada_3_5_mic:           number;
}

export enum VESA {
    Empty = "-",
    NoIncluye = "No incluye",
    The100X100 = "100x100",
    The200X200 = "200x200",
    The400X300 = "400x300",
    The400X400 = "400x400",
    The75X75 = "75x75",
}

export enum Resolucion {
    The1366X768 = "1366x768",
    The1920X1080 = "1920x1080",
    The2560X1080 = "2560x1080",
    The2560X1440 = "2560x1440",
    The2560X2880 = "2560x2880",
    The3440X1440 = "3440x1440",
    The3840X2160 = "3840x2160",
}

export enum TipoFuente {
    Externa = "externa",
    Interna = "interna",
}

export interface Mother {
    id_producto:     number;
    modelo:          null | string;
    cpus:            string;
    SATA:            number;
    marca:           null | string;
    _4pines:         number;
    _4plus:          number;
    wmax:            number;
    _24pines:        number;
    PCI:             number;
    nro_pcie:        number;
    PCIE1X:          number;
    nro_agp:         number;
    IDE:             number;
    tipo_multiplaca: string;
    DDR:             number;
    DDR2:            number;
    DDR3:            number;
    DDR4:            number;
    DDR5:            number;
    Chipsets:        string;
    disponible:      number;
    vga:             number;
    HDMI:            number;
    dvi:             string;
    DP:              number;
    w:               number;
    Floppy:          number;
    USB:             number;
    Factor:          TipoGab;
    sodimm:          number;
    m2:              number;
    con_micro:       number;
    id_sub_cate:     number;
    tipo:            TipoCPUEnum;
    activo:          number;
    wifi_integrada:  number;
    sistema_rgb:     MotherSistemaRGB | null;
    usb20_trasero:   number;
    usb30_trasero:   number;
    usb31_trasero:   number;
    ps2:             number;
    lan:             LAN;
    placa_audio:     string;
    anclaje:         string;
    bios_flashback:  number;
    usb_32_trasero:  number;
    usb_type_c:      number;
    pci_e_x4:        number;
    m2_sata:         number;
    m2_nvme:         number;
    tipo_memoria:    PurpleTipo;
    slot_memoria:    number;
}

export enum LAN {
    GigabitLAN101001000MBS = "Gigabit LAN 10/100/1000 Mb/s",
    The10GBS = "10 Gb/s",
    The1GBS = "1 Gb/s",
    The25GBS = "2.5 Gb/s",
    The25GigabitLAN1010010002500 = "2.5 Gigabit LAN 10/100/1000/2500",
}

export enum MotherSistemaRGB {
    ARGBHeaderRGBHeader = "ARGB Header,RGB Header",
    NoIncluye = "No Incluye",
    RGBHeader = "RGB Header",
    RGBHeaderARGBHeader = "RGB Header,ARGB Header",
}

export enum TipoCPUEnum {
    AMD = "AMD",
    Intel = "Intel",
}

export interface Mouse {
    id_producto:             number;
    disponible:              number;
    color:                   string;
    cantidad_de_botones:     number;
    dpi_ajustable:           string;
    dpi_minimo:              null | string;
    dpi_maximo:              number;
    frecuencia_de_respuesta: null | string;
    peso:                    null | string;
    sistema_de_pesas:        string;
    peso_de_las_pesas:       null | string;
    cantidad_de_pesas:       null | string;
    ancho:                   null | string;
    profundidad:             null | string;
    alto:                    null | string;
    tipo_switch:             TipoSwitch | null;
    tipo_sensor:             TipoSensor | null;
    sensor:                  null | string;
    tecnologias_compatibles: null;
    iluminacion:             string;
    bateria_interna:         string;
    pilas:                   null | string;
    inalambrico:             number;
    tipo_cable:              MouseTipoCable | null;
    cable_largo:             null | string;
    cable_desmontable:       string;
    teconologiawifi:         null | string;
    usb_requeridos:          null | string;
    incluye_receptor:        string;
    orientacion:             Orientacion | null;
    ps2_requerido:           string;
    sistema_recargable:      string;
    velocidad_maxima:        number | null;
    aceleracion_maxima:      number | null;
    funda:                   string;
    consolas_compatibles:    null;
    base_de_carga:           string;
    iluminancion_colores:    IluminancionColores | null;
    procesador:              null | string;
    tipo_de_agarre:          null | string;
    agarre_palm_grip:        number;
    agarre_claw_grip:        number;
    agarre_finger_grip:      number | null;
    agarre_ergonomico:       number | null;
    en_combo_con_pad:        number | null;
}

export enum IluminancionColores {
    Azul = "Azul",
    RGB = "RGB",
    Rainbow = "Rainbow",
    SinIluminación = "Sin Iluminación",
}

export enum Orientacion {
    ParaAmbidiestros = "Para ambidiestros",
    ParaDiestros = "Para diestros",
}

export enum MouseTipoCable {
    ParacordUltraLiviano = "Paracord Ultra Liviano",
    Plástico = "Plástico",
    TelaMallada = "Tela mallada",
}

export enum TipoSensor {
    Óptico = "Óptico",
}

export enum TipoSwitch {
    Omron = "Omron",
}

export interface Mousepad {
    id_producto:     number;
    disponible:      number;
    ancho:           number;
    alto:            number;
    grosor:          number;
    tipo_superficie: TipoSuperficie;
    tipo:            MousepadTipo;
    iluminacion:     ColorLuzTecladoEnum | null;
    categoria:       string;
    cargas_wifi:     string;
    hub_usb:         string;
    req_usb:         string;
    control_Led:     MicTipo | null;
}

export enum MousepadTipo {
    EquilibradoMix = "Equilibrado (Mix)",
    PrecisoControl = "Preciso (Control)",
    RápidoSpeed = "Rápido (Speed)",
}

export enum TipoSuperficie {
    CueroSintético = "Cuero sintético",
    Rígido = "Rígido",
    Tela = "Tela",
}

export interface Notebook {
    id_producto:               number;
    nivel_cpu:                 number;
    nivel_gpu:                 number;
    cantidad_ram_integrada:    number | null;
    slot1_disponible:          number;
    slot2_disponible:          number;
    slot_integrado_disponible: null;
    peso:                      number;
    pulgadas_display:          number;
    ancho:                     number;
    profundidad:               number;
    alto:                      number;
    color:                     string;
    optico:                    Optico;
    slot_m2:                   number;
    capacidad_hd:              number;
    tipo_m2:                   TipoM2 | null;
    sistema_operativo:         SistemaOperativo;
    idioma_teclado:            IdiomaTeclado;
    puertos_hdmi:              number;
    puertos_mini_hdmi:         number;
    puertos_vga:               number;
    puertos_dp:                number;
    puertos_usb_2_0:           number;
    puertos_usb_3_0:           number;
    puertos_usb_3_1_a:         number;
    puertos_usb_3_1_c:         number;
    con_bluethooth:            number;
    tipo_wifi:                 TipoWifi;
    puertos_lan:               PuertosLAN;
    tipo_display:              TipoDisplay | null;
    tipo_cpu:                  TipoCPUEnum;
    tipo_gpu:                  TipoGPU;
    resolucion_display:        Resolucion;
    iluminacion_teclado:       number;
    bateria_extraible:         number;
    peso_sin_bateria:          null;
    cantidad_ram_slot1:        number | null;
    cantidad_ram_slot2:        number | null;
    tipo_ram:                  PurpleTipo;
    modelo_gpu:                string;
    gpu_dedicado:              number;
    modelo_cpu:                string;
    familia_cpu:               string;
    capacidad_ssd:             number | null;
    idioma_sistema_operativo:  null | string;
    touch:                     string;
    tipo:                      FluffyTipo;
    padnum:                    string;
    webcam:                    number;
    color_luz_teclado:         ColorLuzTecladoEnum | null;
    lector_de_memorias:        number;
    mem_gpu:                   number | null;
    lector_de_huella:          number;
    tasa_refesco:              number | null;
    formato_ram:               FormatoRAM;
}

export enum FormatoRAM {
    Sodimm = "SODIMM",
}

export enum IdiomaTeclado {
    Empty = "",
    Español = "Español",
    Ingles = "Ingles",
}

export enum Optico {
    SinOptico = "Sin optico",
}

export enum PuertosLAN {
    Gigabit101001000 = "Gigabit 10/100/1000",
    No = "No",
    Si = "Si",
}

export enum SistemaOperativo {
    Empty = "",
    FreeDOS = "FreeDOS",
    Windows10Home64Bits = "Windows 10 Home 64bits",
    Windows11Home = "Windows 11 Home",
    Windows11Pro = "Windows 11 Pro",
}

export enum FluffyTipo {
    Notebook = "Notebook",
}

export enum TipoDisplay {
    IPS = "IPS",
    OLED = "OLED",
    Tn = "TN",
}

export enum TipoGPU {
    AMDIntegratedGraphics = "AMD Integrated Graphics",
    IntelHDGraphic = "Intel HD Graphic",
    IntelIntegratedGraphics = "Intel Integrated Graphics",
    NVidiaGeForce = "nVidia GeForce",
    NvidiaGeForce = "Nvidia GeForce",
}

export enum TipoM2 {
    Nvme = "NVME",
}

export enum TipoWifi {
    NormaAC = "Norma AC",
    NormaAX = "Norma AX",
}

export interface Teclado {
    id_producto:                   number;
    disponible:                    number;
    swich_type:                    null | string;
    switch_spe:                    null | string;
    tipo_teclado:                  TipoTeclado;
    iluminacion:                   TecladoIluminacion | null;
    con_pad_numerico:              string;
    tecnologias_compatibles:       TecnologiasCompatibles | null;
    puertos_usb_hb:                null | string;
    tipo_cable:                    TecladoTipoCable | null;
    cable_extraible:               string;
    ancho:                         string;
    profundidad:                   string;
    alto:                          string;
    antisalpicadura:               string;
    idioma:                        Idioma | null;
    distribucion:                  Distribucion | null;
    antighosting:                  string;
    peso:                          null | string;
    reposamunecas:                 string;
    reposamunecas_extraible:       string;
    color:                         string;
    cantidad_macros_cargar:        null | string;
    cantidad_teclas_en_simultaneo: null | string;
    conexion:                      string;
    puertos_ps2:                   number;
    bluetooth:                     number;
    receptor_bluetooth:            number;
    wifi:                          string;
    bateria:                       Bateria | null;
    tipo_mecanicos:                TipoMecanicos;
    NKey_Rollover:                 string;
    audio_hub:                     string;
    funda:                         number;
    material:                      Material;
    polling_rate:                  null | string;
    procesador:                    null | string;
    tiempo_de_respuesta:           null | string;
    memoria:                       null | string;
    largo_del_cable:               null | string;
    touchpad:                      string;
    alcance_wifi:                  null;
    pilas_incluida:                null | string;
    ancho_sin_pad:                 null;
}

export enum Bateria {
    BateríaInterna = "Batería interna",
    Empty = "",
    The2PilasAAA = "2 pilas AAA",
}

export enum Distribucion {
    España = "España",
    EstadosUnidos = "Estados Unidos",
    Latinoamerica = "Latinoamerica",
}

export enum Idioma {
    Español = "Español",
    Inglés = "Inglés",
}

export enum TecladoIluminacion {
    RGB = "RGB",
    Rainbow = "Rainbow",
    SinIluminación = "Sin iluminación",
}

export enum Material {
    Aluminio = "Aluminio",
    AluminioPlástico = "Aluminio,Plástico",
    MetalPlástico = "Metal,Plástico",
    Plástico = "Plástico",
    PlásticoAluminio = "Plástico,Aluminio",
    PlásticoMetal = "Plástico,Metal",
}

export enum TecnologiasCompatibles {
    LogitechGHUB = "Logitech G HUB",
    SoftwarePropio = "Software propio",
}

export enum TecladoTipoCable {
    MalladoDeTela = "Mallado de tela",
    Plástico = "Plástico",
}

export enum TipoMecanicos {
    Mecánico = "Mecánico",
    Membrana = "Membrana",
    OptoMecanico = "Opto-Mecanico",
}

export enum TipoTeclado {
    Compacto60 = "Compacto 60%",
    Compacto70 = "Compacto 70%",
    CompactoTKL = "Compacto TKL",
    Completo = "Completo",
}

export interface Video {
    id_producto:     number;
    tipo_multiplaca: TipoMultiplaca;
    capacidad:       number;
    disponible:      number;
    chipset:         string;
    modelo:          null | string;
    marca:           null | string;
    vel_core:        number | null;
    vel_mem:         number | null;
    tipo:            VideoTipo;
    tipo_mem:        TipoMem;
    puente_id:       number | null;
    doble_puente:    number;
    w:               number | null;
    _6pines:         number;
    _2plus:          number;
    hdmi:            number;
    vga:             number;
    DP:              number;
    DVI:             number;
    w_total:         number;
    dvi_analogico:   number;
    rca:             number;
    svideo:          number | null;
    usbtypec:        number | null;
    video_in:        number;
    mem_bits:        number;
    altura:          number;
    ancho:           number | null;
    largo:           number | null;
    espesor:         number | null;
    backplate:       number;
    block_vga_water: number;
    vel_cor_turbo:   number | null;
    cant_cooler:     number | null;
    tipo_procesos:   TipoProcesos;
    cant_procesos:   number | null;
    nivel_gpu:       number | null;
    tecnologia:      null | string;
}

export enum VideoTipo {
    Pcie = "pcie",
}

export enum TipoMem {
    Gddr5 = "GDDR5",
    Gddr6 = "GDDR6",
    Gddr6X = "GDDR6X",
}

export enum TipoMultiplaca {
    Crossfire = "Crossfire",
    Empty = "-",
    SLI = "SLI",
}

export enum TipoProcesos {
    Cuda = "CUDA",
    Empty = "",
    Stream = "Stream",
}
